//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::{
    account_config::Entity as AccountConfig, account_info::Entity as AccountInfo, strategy_config::Entity as StrategyConfig,
    system_config::Entity as SystemConfig,
};
