//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "strategy_config")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub description: String,
    pub status: String,
    pub is_deleted: bool,
    pub trade_mode: String,
    pub nodes: Option<Json>,
    pub edges: Option<Json>,
    pub live_chart_config: Option<Json>,
    pub backtest_chart_config: Option<Json>,
    pub create_time: DateTimeUtc,
    pub update_time: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
