//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "mt5_account_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub account_id: i32,
    pub login: i64,
    pub trade_mode: String,
    pub leverage: i64,
    pub limit_orders: i64,
    pub margin_stopout_mode: String,
    pub trade_allowed: bool,
    pub dlls_allowed: bool,
    pub terminal_connected: bool,
    pub trade_expert: bool,
    pub margin_mode: String,
    pub currency_digits: i64,
    pub fifo_close: bool,
    #[sea_orm(column_type = "Double")]
    pub balance: f64,
    #[sea_orm(column_type = "Double")]
    pub credit: f64,
    #[sea_orm(column_type = "Double")]
    pub profit: f64,
    #[sea_orm(column_type = "Double")]
    pub equity: f64,
    #[sea_orm(column_type = "Double")]
    pub margin: f64,
    #[sea_orm(column_type = "Double")]
    pub margin_free: f64,
    #[sea_orm(column_type = "Double")]
    pub margin_level: f64,
    #[sea_orm(column_type = "Double")]
    pub margin_so_call: f64,
    #[sea_orm(column_type = "Double")]
    pub margin_so_so: f64,
    #[sea_orm(column_type = "Double")]
    pub margin_initial: f64,
    #[sea_orm(column_type = "Double")]
    pub margin_maintenance: f64,
    #[sea_orm(column_type = "Double")]
    pub assets: f64,
    #[sea_orm(column_type = "Double")]
    pub liabilities: f64,
    #[sea_orm(column_type = "Double")]
    pub commission_blocked: f64,
    pub name: String,
    pub server: String,
    pub currency: String,
    pub company: String,
    pub created_time: DateTimeUtc,
    pub updated_time: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
