//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "order")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub order_id: i32,
    pub strategy_id: i32,
    pub exchange: String,
    pub symbol: String,
    pub order_side: String,
    pub order_status: String,
    pub order_type: String,
    #[sea_orm(column_type = "Float")]
    pub quantity: f32,
    #[sea_orm(column_type = "Float")]
    pub price: f32,
    #[sea_orm(column_type = "Float", nullable)]
    pub sl: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub tp: Option<f32>,
    pub created_time: DateTimeUtc,
    pub updated_time: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
