//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "account_config")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub account_name: String,
    pub exchange: String,
    pub is_available: bool,
    pub is_delete: bool,
    pub sort_index: i32,
    pub account_config: Json,
    pub create_time: DateTimeUtc,
    pub update_time: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
