//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "position")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub strategy_id: i64,
    pub node_id: String,
    pub exchange_position_id: i64,
    pub account_id: i32,
    pub exchange: String,
    pub symbol: String,
    pub position_side: String,
    pub position_state: String,
    #[sea_orm(column_type = "Double")]
    pub quantity: f64,
    #[sea_orm(column_type = "Double")]
    pub open_price: f64,
    #[sea_orm(column_type = "Double", nullable)]
    pub unrealized_profit: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub sl: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub tp: Option<f64>,
    pub extra_info: Option<Json>,
    pub created_time: DateTimeUtc,
    pub updated_time: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
