//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "transaction")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub strategy_id: i64,
    pub node_id: String,
    pub exchange: String,
    pub symbol: String,
    pub exchange_position_id: i64,
    pub exchange_transaction_id: i64,
    pub exchange_order_id: i64,
    pub transaction_type: String,
    pub transaction_side: String,
    #[sea_orm(column_type = "Double")]
    pub quantity: f64,
    #[sea_orm(column_type = "Double")]
    pub price: f64,
    pub created_time: DateTimeUtc,
    pub extra_info: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
